name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOURCE_IMAGE: flatcar_production_qemu_image.img
  SOURCE_IMAGE_URL: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_qemu_image.img
  TARGET_IMAGE: flatcar_production_proxmoxve_image.img

# don't waste job slots on superseded code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install APT dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qemu-utils

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Flatcar QEMU image
        run: curl -fsSL $SOURCE_IMAGE_URL > $SOURCE_IMAGE

      - name: Download prebuilt Afterburn RPM
        uses: robinraju/release-downloader@v1.8
        with:
          repository: enix/afterburn
          latest: true
          fileName: '*.rpm'
          tarBall: false
          zipBall: false
          out-file-path: 'rpms'

      - name: Extract Afterburn binary from RPM
        run: |
          export AFTERBURN_RPM_NAME=$(ls rpms | grep -v debug | grep -v dracut | grep -v rust)
          rpm2cpio rpms/$AFTERBURN_RPM_NAME | cpio -idmv
          cp ./usr/bin/afterburn .

      - name: Build image
        run: ./scripts/build_image.sh $SOURCE_IMAGE $TARGET_IMAGE

      - name: Archive image
        uses: actions/upload-artifact@v3
        with:
          # for some unknown reason env variables cannot be used here :(
          name: flatcar_production_proxmoxve_image.img
          path: flatcar_production_proxmoxve_image.img
